### ISSUE TITLE
Angular 18 error Initialize mini app first

### ISSUE THREAD

**Issue by sergio-ser** [m1cron-labs/ng-telegram-mini-app#1]
When I do start use this in Angular 18 like this I got this error.

Can you say me how to fix it?

ERROR Error: Telegram context not found. Initialize mini app first: https://core.telegram.org/bots/webapps#initializing-mini-apps

```
export class AppComponent implements OnInit, OnDestroy {
    private readonly telegram = inject(TelegramWebApp)

    constructor() {
        this.telegram.ready()
    }

    ngOnInit() {
        console.debug('Telegram Web App is ready', this.telegram.initDataUnsafe)
    }

    ngOnDestroy(): void {
        this.telegram.close()
    }
}
```

**Comment by nikes** [comment]
Have you fulfilled this prerequisites?
https://github.com/m1cron-labs/ng-telegram-mini-app?tab=readme-ov-file#prerequisites

**Comment by sergio-ser** [comment]
> Have you fulfilled this prerequisites? https://github.com/m1cron-labs/ng-telegram-mini-app?tab=readme-ov-file#prerequisites

Sure

**Comment by sergio-ser** [comment]
I think the problem is in ssr how to use this package with ssr(Server side rendering) in Angular 18?

**Comment by nikes** [comment]
Try using this https://angular.dev/guide/ssr#authoring-server-compatible-components
